###
GET http://localhost:4000/user-api/user

###
GET http://localhost:4000/user-api/users/haradeeps119@gmail.com

###
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "height":184,
    "weight": 70,
    "age": 20,
    "desiredweight":74,
    "gender":"Male",
    "firstName": "Rishi",
    "lastName": "Varma",
    "email": "rishivamra.d@gmail.com",
    "profileImageUrl":"dfgfdgdf",
    "userProducts":[{"title":"dkfkldsj"}],
    "cost":0
}

###
PUT http://localhost:4000/user-api/users/67d679640753b18bead4e780
Content-Type: application/json

{
    "height":182,
    "weight": 71,
    "age": 20,
    "desiredweight":69,
    "gender":"Male",
    "firstName": "Rishi",
    "lastName": "Varma",
    "email": "rishi@gmail.com",
    "profileImageUrl":"dfgfdgdf",
    "userProducts":[{"title":"dkfkldsj"}],
    "cost":0
}

###get all plans
GET http://localhost:4000/plan-api/plan

###get plan by calories
GET http://localhost:4000/plan-api/plan/1600


###create new plan
POST http://localhost:4000/plan-api/plans
Content-Type: application/json

{
    "id":1,
    "calories":1600,
    "veg":{
        "breakfast":["idk"], 
        "lunch":["idk"], 
        "snacks":["idk"], 
        "dinner":["idk"]
    }, 
    "nonveg":{
        "breakfast":["idk"], 
        "lunch":["idk"], 
        "snacks":["idk"], 
        "dinner":["idk"]
    }
}


###get all products
GET http://localhost:4000/product-api/product

###get product by id
GET http://localhost:4000/product-api/product/67d6ea70fd31443e80d88123

###create product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "img":"https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwi79pPr5ZKMAxXzqGYCHWa3BxgYABALGgJzbQ&co=1&gclid=Cj0KCQjwkN--BhDkARIsAD_mnIquWTAFvKYnglKhbow9w3upY1q3f-PYW4VbfC1xBu_m3uhfGOpZXzEaArLUEALw_wcB&ohost=www.google.com&cid=CAESVeD2JZTPhYmltUNffpu4hWOT76rUEgLBE-bGmz4BZBai0c6NvWgl5NDdvAUPawJS8BZRu1p41heZYmvULFClQ72g0-TEgzvNDTmL9USJFBgn21jTFms&sig=AOD64_2iAejTu70b9oHGjQuZ6FPqkGEYzA&ctype=5&q=&ved=2ahUKEwjc8o7r5ZKMAxWAXGwGHTnvDFMQ9aACKAB6BAgJEDY&adurl=",
    "title":"Creatine",
    "description":"Boost up your enrgy",
    "price":800,
    "id":10
}